version: '3.8'

services:
        frontend-service:
                build:
                        dockerfile: Dockerfile
                        context: ./1.12
                container_name: frontend
                ports:
                        - "5000:5000"
        backend-service:
                build:
                        dockerfile: Dockerfile
                        context: ./1.13
                container_name: backend
                ports:
                        - "8080:8080"
                environment:
                        - REQUEST_ORIGIN=http://localhost
                        - REDIS_HOST=redis
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DATABASE=postgres
                        - POSTGRES_HOST=db
        redis:
                image: redis
        db:
                image: postgres:13.2-alpine
                restart: unless-stopped
                volumes:
                        - ./database:/var/lib/postgresql/data
                environment:
                        - POSTGRES_PASSWORD=postgres
                depends_on:
                        - backend-service
                container_name: postgres_db
        web:
                image: reverseproxy
                restart: always
                ports:
                       - "80:80"